// <auto-generated />
namespace Project2WooxTravel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class newtableadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newtableadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202410081824453_new-table-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
